title: Eneko Uruñuela
include: ["_pages", "api"]
exclude: ["_includes/notes_graph.json", "node_modules", ".vercel"]

baseurl: ""
url: "https://eurunuela.github.io"
permalink: /:title/

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
use_html_extension: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

relative_permalinks: false

# Remove GitHub Pages specific settings
# github_pages: true  <-- Remove this linedified-at

# Remove environment-specific settings
# environment: production
# future: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir: _sass
  style: :compressed
  notes:
    output: true
    permalink: /notes/:title/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: "_notes"
    values:
      layout: "note"

# Debug settings
show_drafts: true
verbose: true
