name: Fetch Scholar and GitHub data
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch GitHub data
        run: |
          curl -L -X POST 'https://api.github.com/graphql' \
          -H 'Authorization: bearer ${{ secrets.API_KEY }}' \
          --data-raw '{"query":"{\n  user(login: \"eurunuela\") {\n pinnedItems(first: 6) {\n totalCount\n edges {\n node {\n ... on Repository {\n name\n id\n url\n stargazers {\n totalCount\n }\n description\n }\n }\n }\n }\n }\n }"' \
          -o github_data.json
      - name: Checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Fetch Scholar data
        run: |
          pip3 install scholarly
          python3 workflows/fetch_from_scholar.py
      - name: Commit fetched data files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "Update fetched data"
          git push
