name: Fetch Scholar and GitHub data
on:
  schedule:
    - cron: "0 12 6 * *"
  workflow_dispatch:
jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Scholar data
        run: |
          python3 .github/workflows/fetch_from_scholar.py
        working-directory: .
      - name: Fetch GitHub data
        run: |
          sh .github/workflows/fetch_from_github.sh
        working-directory: .
