name: Fetch Scholar and GitHub data
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Scholar data
        run: |
          pwd
          ls
          pip3 install scholarly
          python3 workflows/fetch_from_scholar.py
      - name: Fetch GitHub data
        run: |
          sh workflows/fetch_from_github.sh
      - name: Commit fetched data files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "Update fetched data"
          git push
